### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Wangyfeng** [Depado/goploader#102]
hi, I have compiled server and encountered an issue during execution, but when I downloaded the v1.0 file and executed it, I did not encounter this issue
 `./server`
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6ea240]

goroutine 1 [running]:
debug/elf.(*Section).ReadAt(0xc000480000?, {0xc0001c5200?, 0x10400?, 0xc00040c000?}, 0x133f4d9?)
	<autogenerated>:1 +0x20
archive/zip.readDirectoryEnd({0xc83f40, 0xc0003f7400}, 0x214)
	/usr/local/go/src/archive/zip/reader.go:576 +0xf9
archive/zip.(*Reader).init(0xc000466150, {0xc83f40?, 0xc0003f7400}, 0x214)
	/usr/local/go/src/archive/zip/reader.go:119 +0x50
archive/zip.NewReader({0xc83f40, 0xc0003f7400}, 0x214)
	/usr/local/go/src/archive/zip/reader.go:112 +0x5e
github.com/daaku/go%2ezipexe.zipExeReaderElf({0xc83b80?, 0xc00004ede8}, 0x134f8d9)
	/home/user/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.1/zipexe.go:128 +0x85
github.com/daaku/go%2ezipexe.NewReader({0xc83b80, 0xc00004ede8}, 0x0?)
	/home/user/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.1/zipexe.go:48 +0x91
github.com/daaku/go%2ezipexe.OpenCloser({0xc000390e00?, 0xc0002afd40?})
	/home/user/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.1/zipexe.go:30 +0x56
github.com/GeertJohan/go%2erice.init.0()
	/home/user/go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.2/appended.go:42 +0x4f
` 
Thanks in advance

**Comment by Depado** [comment]
Hello
I'm sorry but this project has not really been maintained for the past few years. My guess is that one of the libraries has been updated and messes with legacy code. I'll try to have a look but this is a really old project that I intended to rewrite at some point.

**Comment by Depado** [comment]
Did you embed the files using `rice` before starting the server?

**Comment by Wangyfeng** [comment]
I did not use rice, my go version is 1.21.6
I just execute the command `make` and then  `cd server/` to starting the server `./server`

**Comment by Wangyfeng** [comment]
Hello, I think I have identified the issue and the reason may be that my go version is too high. I tried lowering the go version to 1.18 and found that it can now run normally `./server`
Thank you again for your help
