### ISSUE TITLE
Implement storage limit

### ISSUE THREAD

**Issue by Depado** [Depado/goploader#14]
As of today there is no limit for the total size of files that are stored on the server. Would be a nice feature to limit to a certain size, and delete older files if that limit is broken

**Comment by simonqbs** [comment]
Hi,
This a feature I really needed so I have implemented a simple solution in [my fork](https://github.com/simonqbs/goploader/tree/quota). My implementation doesn't delete older files when quota is exceeded though.

**Comment by Depado** [comment]
Hi,
Nice implementation, I may implement my own later though. If you wish you can create a pull request so I can remember the way you did things ? 

Goploader is subject to heavy changes in the next weeks, especially on the statistics module by the way.

Cheers and thanks for the implementation example :+1:

**Comment by simonqbs** [comment]
Sure, a pr created.

**Comment by Depado** [comment]
Commented on your PR :)

**Comment by Depado** [comment]
I had a closer look and tested a bit further, thing is, you're dependent on the header (which the client doesn't provide). To know the exact size of the thing being uploaded you'll have to check the `wr` variable which contains the exact number of bytes that were written on disk. I'm currently working on integrating that, but that adds another step (if the file is too large, it is first written and then deleted). 

That's the only safe way I found actually. Anyone can tamper the header :/

**Comment by Depado** [comment]
The issue is now fixed. I implemented it my own way by checking the written bytes, and reworked a little on how the stats are saved (they are now saved in the same transaction as the resources). Thanks for the help ! :) Website will get an update soon.

**Comment by simonqbs** [comment]
That's great :) Your solution looks much better.

**Comment by Depado** [comment]
Thanks I'm glad you like it ! I got inspired by your work :)

Pushing the website with updated documentation right now.
