### ISSUE TITLE
Do not open in browser

### ISSUE THREAD

**Issue by rka** [Depado/goploader#30]
Hello,

First i would like to thank you for your hard work this is an awesome project :)

Is it possible to have the downloads not open in the browser, Like txt and video files ?

**Comment by Depado** [comment]
Hi,
First of all, thanks for your support. 

I think it's more about the way your browser handle files. Files it doesn't know how to open it will offer to download. Is it really an issue ? You could always right click on the page and click the “Save the page as...” or directly `wget` the link. I could work something out though if that's really an issue. 

Cheers :)

**Comment by rka** [comment]
Thanks for the quick reply. 
Yes if the link is sent or displayed in a browser like in a webpage you can left click and save as... but when someone gets the link in outlook you don't have that option. But its absolutely not a big deal just would be easier. So if its a big hurdle don't sweat it :)

**Comment by Depado** [comment]
Always serving a downloadable file is easy. But that would apply for images, videos and all the other formats too. Up to you. I'll add an option in the configuration file.

**Comment by rka** [comment]
That would be awesome!! :) Thanks

**Comment by Depado** [comment]
Just out of curiosity, are you self-hosting the application ? Because even if I add an option, I don't intend to activate it on up.depado.eu :)

**Comment by rka** [comment]
Yes i do self host it. You can check it out [here](feltoltes.erzsebetvaros.hu) :) 
Changed the language and color and added a banner, it was super easy to work with i love it.

**Comment by Depado** [comment]
Amazing how you tweaked it ! Love it :)
I'm adding the option soon.

**Comment by Depado** [comment]
Hi,
There is now an option you can add in your `conf.yml` file which is `always_download`. This option when set to `true` will set the `Content-Type` header to `application/octet-stream` which will force browsers to offer to download the file and not display them. Download page is up to date.

The documentation has been updated, see https://up.depado.eu/#server-setup-conf (Also added some examples on how to use with Caddy, Apache, Systemd)

**Comment by rka** [comment]
thanks i updated your changes and its working gr8 :)

**Comment by Depado** [comment]
You're welcome, don't hesistate to post other issues if you see other improvements I could made ! Always happy to help :D
