### ISSUE TITLE
change temporarily folder?

### ISSUE THREAD

**Issue by bioryb** [Depado/goploader#31]
Hi,
I am just testing goploader. Now, I will use it for uploading big files (~20GB-50GB).

On my first test I figured out, that the files are temporarily stored in /tmp (using Debian 8). Is there a way to change this to another directory?

Thanks in advance and really thank you for this piece of software!!

Ronny

**Comment by Depado** [comment]
Are you talking about the client or the server side ?

On the server side I will have to investigate because I don't remember (and a quick search confirmed that) using the `/tmp` path anywhere in the code.

**Comment by bioryb** [comment]
I am talking about the server side. But maybe a flag to configure would be fine for the client, too.
The problem is, that I have a lot of space for the file storage, but not for /tmp :-/

Would be great if there could be a flag to configure where to place temp files.

**Comment by Depado** [comment]
I'll investigate on that. I don't remember using `/tmp` at all on the server side, so I guess that comes from the encryption lib or something like that.

**Comment by bioryb** [comment]
Hi,
just checked if this has gone if encryption is disabled - no.

Just for your information

**Comment by Depado** [comment]
Mind if I ask if you have a webserver in front of Goploader ? (I'm using Caddy)

**Comment by bioryb** [comment]
Actually for testing I do not use a webserver in front of goploader.

However, this may not have any impact on this issue?!?!

**Comment by Depado** [comment]
Just checking. This may not impact this issue indeed.

**Comment by bioryb** [comment]
Hi,
did you find anything on this issue?
Actually, this is the only show stopper for me.

This morning I did a `strace` to find any hint in this, but I did not get anything.

**Comment by Depado** [comment]
Hi,
Currently I have little time to work on goploader, so no, not yet. I'm sorry this stops you :/

**Comment by Depado** [comment]
This is just for me as a reminder : 

- [golang.org/src/mime/multipart/formdata.go](https://golang.org/src/mime/multipart/formdata.go#L72)
- [ioutil.TempFile](https://golang.org/pkg/io/ioutil/#TempFile)
- [os.TempDir](https://golang.org/pkg/os/#TempDir)
- [golang.org/src/os/file_unix.go](https://golang.org/src/os/file_unix.go?s=9565:9586#L336)

So ! 

SOLUTION : Set the environment variable `TMPDIR` to the absolute path of your `upload_dir` configuration variable and you're good to go. I guess. I'll try that later.

**Comment by bioryb** [comment]
That works!

Great! Thank YOU!
