### ISSUE TITLE
Disable encryption to speed up?

### ISSUE THREAD

**Issue by bioryb** [Depado/goploader#32]
Hi once again :)
Does it make sense to disable encryption if not needed to speed up the down/upload? Actually I cannot disable encryption - so I cannot test this :-/

Best regards
Ronny

**Comment by Depado** [comment]
That's kind of the philosophy of goploader actually. But I could work something out to disable encryption. Can I give you a binary without the encryption part so you can benchmark it ? (I don't have one but I don't think it would be complicated to remove that part, also that's less complicated than modifying the whole code structure to add a flag in the config file)

**Comment by bioryb** [comment]
If you could provide me a binary I will try to benchmark this. No problem.

**Comment by Depado** [comment]
Which OS/Arch are you running the server on ? I assume Linux 64Bit, I'll give that to you in a few hours :)

By the way, thanks for the feedback ;)

**Comment by bioryb** [comment]
Hi, I'm running Debian 8, 64bit.

Thanks for your support ;)

**Comment by Depado** [comment]
I'll just add an option in the configuration file, that sounds easier than the whole refactoring just to produce a binary. I'll tell you when it's up. Something like `disable_encryption` in the configuration file that will override all the encryption settings.

**Comment by bioryb** [comment]
sounds really simple and effective.

THX!

**Comment by Depado** [comment]
Feature is now live, if you want to build from source and try it out/benchmark. The option has been added to the setup, so you can simply `go build` and `./server --initial` to disable encryption, or add the following line to your `conf.yml` : `disable_encryption: true`

**Comment by Depado** [comment]
Also if you benchmark, could you post the result of your investigations ? :D

**Comment by bioryb** [comment]
Hi,
here are my results (2.7GB file).

with encryption:
real	5m44.464s
user	0m5.036s
sys	0m9.659s

without encryption:
real	4m42.609s
user	0m4.789s
sys	0m9.505s

To test I used "time goploader_client -p <file>"

**Comment by Depado** [comment]
Thanks for the benchmark :+1:
