### ISSUE TITLE
Feature Request: Show upload progress?

### ISSUE THREAD

**Issue by bioryb** [Depado/goploader#34]
As you can see I'm really working on goploader :)

Is there a possibility to show a progress bar (or something like) on a running upload?

THX and have a nice weekend

**Comment by Depado** [comment]
You mean in the web UI ? I could have a look. Otherwise there is already a progress bar in the terminal client.

**Comment by bioryb** [comment]
Yes, in the webui. Would bei nice ;-)

Terminal client is perfect!

**Comment by bioryb** [comment]
The terminal client feature makes goploader unique and really cool

I hope it is ok to mail you some more imporvements/feature requests :)

**Comment by Depado** [comment]
Sure it's ok :) Please do, I'm glad you have such a strong interest in my project ! :+1:

**Comment by bioryb** [comment]
When the new release is out (and hopefully my feature requests included;) ) I will write an article on my blog on goploader. Deal?

**Comment by Depado** [comment]
Sure thing :+1:

**Comment by bioryb** [comment]
Works like a charm :+1:

**Comment by rka** [comment]
Hello awesome feature :) Is there a way update to this version and don't loose my language changes? Or i should just do it manually

**Comment by Depado** [comment]
You could patch your HTML files with those changes : https://github.com/Depado/goploader/commit/38fa7a79ed4a884614f3fd8f4b926fff1d945fcd

(`custom.js`, `index.html` and `style.css` changes, the other changes aren't relevant)

**Comment by rka** [comment]
Yes i did that, working OK now. If its not a huge work maybe there could be a language file so we can have all the visible parts there then its easy to manage in the future.

**Comment by Depado** [comment]
Please open another feature request ^^ (Just so I can keep tracks of those)
