### ISSUE TITLE
README.md Documentation

### ISSUE THREAD

**Issue by Depado** [Depado/goploader#38]
As for now the only documentation available is on [gpldr.in](https://gldr.in), that would be better to have a real documentation in the `README.md` file in the repo, in case [gpldr.in](https://gpldr.in) is taken down for whatever reason.

**Comment by daftaupe** [comment]
Hello,

Wouldn't it be better to have the documentation in the Wiki section of the repo ?
I see that a few sections have been started.

**Comment by daftaupe** [comment]
Thanks, I just discovered the language highlighting feature and line numbering.
I can help exporting the doc I guess, I have some time.

**Comment by Depado** [comment]
I don't know if that's possible though.
Don't worry I'll do it ;)

**Comment by daftaupe** [comment]
Alright, thanks !

**Comment by Depado** [comment]
Done ☺ Some links are not working though. I'll fix this later. For now https://docs.gpldr.in is still the preferred way to get the documentation.
