### ISSUE TITLE
Caddyfile review

### ISSUE THREAD

**Issue by Fastidious** [Depado/goploader#51]
The `Caddyfile` for Caddy web server should be:

```
up.example.com {
	proxy / 127.0.0.1:8002 {
		transparent
	}
	gzip
}
```

**Comment by Depado** [comment]
Indeed you're right ! Thanks 🎉

**Comment by Depado** [comment]
![test](https://media.giphy.com/media/HJ8NsNtn9VswE/giphy.gif)

And voilà
