### ISSUE TITLE
Installation error - cannot use "github.com/boltdb/bolt".Options literal

### ISSUE THREAD

**Issue by karibuTW** [Depado/goploader#66]
Hello,
I've installed Go 1.10, following this tutorial (For Debian 9)
https://tecadmin.net/install-go-on-debian/
and I'm trying now to install goploader, however when I run 
`go get github.com/Depado/goploader/server`
or
`go build github.com/Depado/goploader/server`

I have the following error:
```
# github.com/Depado/goploader/server/database
Projects/Proj1/src/github.com/Depado/goploader/server/database/database.go:18:79: cannot use "github.com/boltdb/bolt".Options literal (type *"github.com/boltdb/bolt".Options) as type *"github.com/coreos/bbolt".Options in argument to storm.BoltOptions
```

And thus I don't see the .server binary.

Any advice?

Thank you

**Comment by tribut** [comment]
You need to fetch the right version of the dependencies. The easiest way is to use dep:

~~~
curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
cd $GOPATH/src/github.com/Depado/goploader/
dep ensure
~~~

**Comment by karibuTW** [comment]
Thank you,

So on the installation steps, you confirm I should do:
```
go get github.com/Depado/goploader/server
curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
cd $GOPATH/src/github.com/Depado/goploader/
dep ensure
go build github.com/Depado/goploader/server
```
?
Because doing so will trigger this issue:

> go build github.com/Depado/goploader/server: build output "server" already exists and is a directory

Not sure what should be the correction.

Thank you

**Comment by tribut** [comment]
Almost. You are trying to create the binary `server` in the folder `$GOPATH/src/github.com/Depado/goploader` but the directory `server` already exists there. So either give the server a different name or go to a different directory before building.

~~~
go build -o ~/goploader-server github.com/Depado/goploader/server
~~~

**Comment by Depado** [comment]
Or you can also 

```
$ cd $GOPATH/src/github.com/Depado/goploader/server
$ go build
```

Or look at the `Makefile` and simply `make` (this will also compile the client)
