### ISSUE TITLE
How can i make it support the format of SWF?

### ISSUE THREAD

**Issue by Jupiterss** [Depado/goploader#68]
The title says it all.....
In addition ,  I wonder if i could watch SWF format on Browser without downloading it.

**Comment by Depado** [comment]
Hey.
That would require to add an SWF player on the display page which I'm truly not fond of. (Supporting flash and all)

I guess what you could do is embedding that SWF in an HTML page which contains a Flash player. Don't you have an option to export your SWF as an HTML page ?
If you upload an HTML page with goploader, it will display in the browser.

**Comment by Jupiterss** [comment]
> 
> 
> Hey.
> That would require to add an SWF player on the display page which I'm truly not fond of. (Supporting flash and all)
> 
> I guess what you could do is embedding that SWF in an HTML page which contains a Flash player. Don't you have an option to export your SWF as an HTML page ?
> If you upload an HTML page with goploader, it will display in the browser.

I see^^. Thanks a lot for responding.   I do like the contribution of yours .

**Comment by Depado** [comment]
Keep me updated if you find a solution that fits your needs :+1:
