### ISSUE TITLE
Cannot compile latest version from master

### ISSUE THREAD

**Issue by jonathanmarsaud** [Depado/goploader#69]
Hi,

It seems that I can't compile anymore the Goploader server from master:

```
$ go build
# github.com/Depado/goploader/server/database
../../go/src/github.com/Depado/goploader/server/database/database.go:7:2: imported and not used: "go.etcd.io/bbolt"
../../go/src/github.com/Depado/goploader/server/database/database.go:18:59: undefined: bolt
```

Is it intended (for tests, as it seems that this commit is recent: https://github.com/Depado/goploader/commit/ffb85182b42cd76349e4ff110ccfee3685c0d9b9#diff-1e777cb518a26cf47f4e216b8725ce93)?

Thanks anyway for your product!

**Comment by Depado** [comment]
Hey,

Well that's weird. Did you run `dep ensure` before trying to build ? That dependency changed recently, indeed.

Which version of Go are you using ?

**Comment by Depado** [comment]
Hey there. You were right, I did not update the `Gopkg.toml` file to reflect the change I made in the code. In theory, you can pull the repo and get the vendored deps:

```
$ git clone ...
$ cd goploader
$ dep ensure
$ make
```

Sorry about that and thanks for bringing up the issue !

![thanks](https://media.giphy.com/media/3ohs2AdJVxjpr16DxC/giphy.gif)
