### ISSUE TITLE
token : how tu use it

### ISSUE THREAD

**Issue by acaz** [Depado/goploader#71]
Hello 

I'am interresting to using token for upload.
How can we use it for permit upload file on self hosted server ? 

Thx

**Comment by Depado** [comment]
Hi, in your configuration file, just add a key named `token` like so:

```yaml
token: mysupersecrettoken
```

This will automatically enable token usage, meaning all uploads will need to transmit this token before it is allowed to upload content to your self-hosted instance. Does this help?
