### ISSUE TITLE
[Feature request] Allow unlimited duration

### ISSUE THREAD

**Issue by KaKi87** [Depado/goploader#74]
Hello,

I need to provide the simplest image upload service possible for my users and unlimited duration is necessary.

Is it doable ?

Thanks

**Comment by Depado** [comment]
Hello @KaKi87 
Unfortunately goploader doesn't support removing time limit as of now. This project is starting to be a bit old and it's been a while I didn't work on it (I'm honestly considering a full rewrite). I'll see if that's something easy to add and I'll keep you upadted in this issue if that's ok with you :+1:

**Comment by KaKi87** [comment]
Thanks for your answer !
I actually used [linx-server](https://github.com/andreimarcu/linx-server) instead, though it's not privacy-oriented but it's not vital for internal use.
However, I would highly recommend you to add screenshots and/or host a demo of your project so people like me who spend the entire morning comparing a lot of similar projects can work with more ease.

**Comment by Depado** [comment]
You're welcome!
Linx looks like a great project, I didn't know that one, thanks!
There was a "demo" sort of at [gpldr.in](https://gpldr.in), but now I'm using it for only friends and family using a token/password. 
Cheers!
