### ISSUE TITLE
gpldr.in?

### ISSUE THREAD

**Issue by lesion** [Depado/goploader#75]
Connection refused :/

**Comment by Depado** [comment]
Yeah sorry my server has been down for a few days.

**Comment by Depado** [comment]
Should be up again :+1:

**Comment by tete2soja** [comment]
Hello,

I add a comment here because it seems offline again and gives a 502 error.

**Comment by Depado** [comment]
Hello,

Sorry that it's offline, I'm not actively maintaining this project anymore and it requires a massive refactoring. 
Also the main instance has been protected with a token for some time because of some bad actors.

**Comment by tete2soja** [comment]
Ok, I used the embed documentation inside the repo instead of the website!
Thanks!

**Comment by Depado** [comment]
Oh, yes I forgot about the documentation site. 
It's up and running again at https://docs.gpldr.in :+1:
