### ISSUE TITLE
Server Downloads is broken

### ISSUE THREAD

**Issue by benihanaz** [Depado/goploader#78]
https://gpldr.in/#server-downloads directs to the upload page, unable to retrieve server install files

**Comment by Depado** [comment]
Hello, I'm currently in the process of moving some things on a new server. This project will soon use Github releases. Please stay tuned.

**Comment by Depado** [comment]
Hey, quick update, I don't have time to fully migrate to github releases, this project would need a lot of refactoring.
I uploaded the artifacts there https://docs.gpldr.in/server/downloads/
